### ISSUE TITLE
make-terminal always throws an exception in 0.3.0

### ISSUE THREAD

**Issue by m-r-hunt** [aaron-santos/zaffre#3]
Here's the output from trying to run Zaffre's main directly (so I know it's not me).

```
PS E:\clojurestuff\zaffre> lein run
Reflection warning, zaffre/glterminal.clj:95:24 - reference to field getName can't be resolved.
Reflection warning, zaffre/glterminal.clj:95:40 - reference to field getSize can't be resolved.
Reflection warning, zaffre/glterminal.clj:124:46 - call to method canDisplay can't be resolved (target class is unknown).
Reflection warning, zaffre/glterminal.clj:175:7 - call to method setRenderingHint on java.awt.Graphics can't be resolved (no such method).
Reflection warning, zaffre/glterminal.clj:213:24 - reference to field getWidth can't be resolved.
Reflection warning, zaffre/glterminal.clj:214:24 - reference to field getHeight can't be resolved.
Reflection warning, zaffre/glterminal.clj:217:18 - reference to field getRaster can't be resolved.
Reflection warning, zaffre/glterminal.clj:218:18 - reference to field getDataBuffer can't be resolved.
Reflection warning, zaffre/glterminal.clj:220:18 - reference to field getData can't be resolved.
Reflection warning, zaffre/glterminal.clj:221:33 - call to static method alength on clojure.lang.RT can't be resolved (argument types: unknown).
Reflection warning, zaffre/glterminal.clj:271:15 - reference to field getWidth can't be resolved.
Reflection warning, zaffre/glterminal.clj:272:16 - reference to field getHeight can't be resolved.
Reflection warning, zaffre/glterminal.clj:309:7 - call to static method glTexImage2D on org.lwjgl.opengl.GL11 can't be resolved (argument types: int, long, int, unknown, unknown, long, int, int, unknown).
Reflection warning, zaffre/glterminal.clj:355:59 - call to static method aset on clojure.lang.RT can't be resolved (argument types: unknown, int, unknown).
Reflection warning, zaffre/glterminal.clj:361:61 - call to static method aset on clojure.lang.RT can't be resolved (argument types: unknown, int, unknown).
Reflection warning, zaffre/glterminal.clj:362:61 - call to static method aset on clojure.lang.RT can't be resolved (argument types: unknown, int, unknown).
Reflection warning, zaffre/glterminal.clj:446:7 - call to static method glBindAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: int, java.lang.Object, java.lang.Object).
Reflection warning, zaffre/glterminal.clj:446:7 - call to static method glBindAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: int, java.lang.Object, java.lang.Object).
Reflection warning, zaffre/glterminal.clj:486:7 - reference to field flip can't be resolved.
Reflection warning, zaffre/glterminal.clj:498:7 - reference to field flip can't be resolved.
Reflection warning, zaffre/glterminal.clj:633:11 - call to static method glTexImage2D on org.lwjgl.opengl.GL11 can't be resolved (argument types: int, long, int, java.lang.Object, java.lang.Object, long, int, int, unknown).
Reflection warning, zaffre/glterminal.clj:930:68 - call to static method glGetAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, java.lang.String).
Reflection warning, zaffre/glterminal.clj:931:68 - call to static method glGetAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, java.lang.String).
Reflection warning, zaffre/glterminal.clj:932:71 - call to static method glGetAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, java.lang.String).
Reflection warning, zaffre/glterminal.clj:933:71 - call to static method glGetAttribLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, java.lang.String).
Reflection warning, zaffre/glterminal.clj:949:59 - call to static method glGetUniformLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, unknown).
Reflection warning, zaffre/glterminal.clj:962:59 - call to static method glGetUniformLocation on org.lwjgl.opengl.GL20 can't be resolved (argument types: java.lang.Object, unknown).
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - Loading font by name
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - Using font java.awt.Font[family=Consolas,name=Consolas,style=plain,size=18]
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - characters per line 204
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - characters 4650 cwidth 2048 cheight 512
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - glyph image width 2048 height 512
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - arranging character with zaffre.glterminal$characters_per_line@1a1ccaaf per line
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - Created font texture. screen-width 800 screen-height 528
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - screen size 800 x 528
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - byte-buffer [Ljava.nio.ByteBuffer;@510a4cf4
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - Creating glyph array
16-02-29 00:46:14 Max-Desktop INFO [zaffre.glterminal] - creating buffers for glyph/fg/bg textures ( 128 x 32 )
ERROR: Linking Shaders:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated


Exception in thread "main" java.lang.Exception: OpenGL Error(1282):GL_INVALID_OPERATION: glGenBuffers vertices-vbo-id - Invalid operation, compiling:(C:\Users\max\AppData\Local\Temp\form-init5499585173456089547.clj:1:106)
        at clojure.lang.Compiler.load(Compiler.java:7239)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: OpenGL Error(1282):GL_INVALID_OPERATION: glGenBuffers vertices-vbo-id - Invalid operation
        at zaffre.glterminal$except_gl_errors.invoke(glterminal.clj:266)
        at zaffre.glterminal$init_buffers.invoke(glterminal.clj:521)
        at zaffre.glterminal$make_terminal$fn__2943.invoke(glterminal.clj:939)
        at zaffre.glterminal$make_terminal.invoke(glterminal.clj:939)
        at zaffre.glterminal$handle_input_in_main.doInvoke(glterminal.clj:1104)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at zaffre.glterminal$_main.doInvoke(glterminal.clj:1160)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at user$eval2515.invoke(form-init5499585173456089547.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        ... 11 more
```

Then a blank window pops up and I have to do something to kill off the JVM.

It seems to be related to the recent shader fx change. In my project I originally hadn't set the fx-shader-name option, and setting it to retro.fs didn't help.

I'm on 64 bit Windows 10, Java 1.8. If you need any more information or there's any other way I can help debugging let me know.

**Comment by aaron-santos** [comment]
Thank you for the log output. I *think* the cause is due to switching to an OpenGL 3.2 context (from 3.0) which requires a #version header in all shaders (the vertex shader was missing one). https://clojars.org/zaffre/versions/0.3.1-SNAPSHOT 0.3.1-SNAPSHOT includes a fix for this, but I can't yet test it on a windows machine.

**Comment by m-r-hunt** [comment]
I'll try it out when I'm at home tonight (UK time).

**Comment by m-r-hunt** [comment]
That seems to have fixed it for me. Thanks for the quick response Aaron.

**Comment by aaron-santos** [comment]
Sure thing. Thanks for pointing it out and also for your patience. I'll make a note to try out these sorts of changes on a Windows machine before pushing them out.
